mode = "dark"
accent = "#FFB69C"
selection = "#4A3128"
muted = "#A38C7A"

# --- Backgrounds ---
background = "#090706"
dark_background = "#040302"
darker_background = "#000000"
lighter_background = "#100D0C"

# --- Foregrounds ---
foreground = "#F2E3D2"
dark_foreground = "#BEA48D"
light_foreground = "#F6ECDD"
bright_foreground = "#FEF8F0"

# --- Base Colors ---
red = "#E36C73"
orange = "#E89664"
yellow = "#E3C272"
green = "#8FBA7F"
cyan = "#78BDB1"
blue = "#82AEDB"
magenta = "#C98EAF"
brown = "#A37A60"

# --- Bright Colors ---
bright_red = "#ED8489"
bright_orange = "#F2AB80"
bright_yellow = "#EDCE87"
bright_green = "#A1C992"
bright_cyan = "#8DD0C5"
bright_blue = "#99C3ED"
bright_magenta = "#D8A3C1"
bright_brown = "#BA8E72"
